blockchain:
  mspID: Org1MSP
  cryptoPath: /home/liuhd/go/src/github.com/liuhdd/exam-cret/blockchain/test-network/organizations/peerOrganizations/org1.example.com
  certPath: /home/liuhd/go/src/github.com/liuhdd/exam-cret/blockchain/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  keyPath: /home/liuhd/go/src/github.com/liuhdd/exam-cret/blockchain/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/
  tlsCertPath: /home/liuhd/go/src/github.com/liuhdd/exam-cret/blockchain/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  peerEndpoint: localhost:7051
  gatewayPeer: peer0.org1.example.com
  chaincodeName: examcret
  channelName: mychannel