PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `exams` (`exam_id` text,`exam_name` text NOT NULL,`paper` text NOT NULL,`place` text NOT NULL,`begin_time` integer NOT NULL,`end_time` integer NOT NULL,`exam_server` text,`exam_server_key` text,`exam_desc` text,PRIMARY KEY (`exam_id`));
INSERT INTO exams VALUES('exam111','操作系统','A卷','学校',1684166400000,1684252800000,'','','666');
CREATE TABLE `exam_records` (`exam_id` text NOT NULL,`student_id` text NOT NULL,`grade` integer NOT NULL,PRIMARY KEY (`student_id`));
INSERT INTO exam_records VALUES('exam111','student111',20);
CREATE TABLE `questions` (`question_id` text,`question_type` text NOT NULL,`content` text NOT NULL,`solution` text NOT NULL,`score` integer NOT NULL,PRIMARY KEY (`question_id`));
CREATE TABLE `exam_actions` (`object_type` text,`action_id` text,`exam_id` text NOT NULL,`student_id` text NOT NULL,`action_type` integer NOT NULL,`action_time` integer NOT NULL,`question_id` text NOT NULL,`answer` text,PRIMARY KEY (`action_id`));
INSERT INTO exam_actions VALUES('exam_action','action1','exam111','student111',1,1684861200000,'question1','啊飒飒的n');
INSERT INTO exam_actions VALUES('exam_action','action2','exam111','student111',1,1684861200000,'question2','啊飒飒的n');
CREATE TABLE `mark_actions` (`object_type` text,`action_id` text,`exam_id` text NOT NULL,`student_id` text NOT NULL,`question_id` text NOT NULL,`score` integer NOT NULL,`scorer` text NOT NULL,`scored_time` integer NOT NULL,PRIMARY KEY (`action_id`));
INSERT INTO mark_actions VALUES('mark_action','mark_action1','exam111','student111','question2',10,'liuhd',1678293569);
CREATE TABLE `marks` (`exam_id` text NOT NULL,`student_id` text NOT NULL,`question_id` text NOT NULL,`answer` text,`score` integer,PRIMARY KEY (`exam_id`,`student_id`,`question_id`));
INSERT INTO marks VALUES('exam111','student111','question1','啊飒飒的n',10);
INSERT INTO marks VALUES('exam111','student111','question2','啊飒飒的n',10);
CREATE TABLE `users` (`user_id` text,`username` text NOT NULL UNIQUE,`password` text NOT NULL,`role` text,`update_time` integer NOT NULL,`last_login_time` integer NOT NULL,PRIMARY KEY (`user_id`));
INSERT INTO users VALUES('student111','student111','123456','student',0,0);
INSERT INTO users VALUES('','amdin','admin','',0,0);
INSERT INTO users VALUES('admin','amdinn','admin','',0,0);
INSERT INTO users VALUES('123','123','123','',0,0);
CREATE TABLE `students` (`user_id` text,`username` text NOT NULL UNIQUE,`password` text NOT NULL,`role` text,`update_time` integer NOT NULL,`last_login_time` integer NOT NULL,`student_id` text NOT NULL UNIQUE,`name` text NOT NULL,`gender` text,`email` text,`phone` text,PRIMARY KEY (`user_id`));
INSERT INTO students VALUES('student111','student111','123456','student',0,0,'student111','张三','男','123@123.com','10086');
CREATE TABLE `teachers` (`user_id` text,`username` text NOT NULL UNIQUE,`password` text NOT NULL,`role` text,`update_time` integer NOT NULL,`last_login_time` integer NOT NULL,`teacher_id` text NOT NULL,`name` text NOT NULL,`gender` text,`email` text,`phone` text,PRIMARY KEY (`user_id`));
COMMIT;
